Задачи: Основы JS. Примитивные типы данных
js-tasks-ru/js-20220909_mikrit pull request #2
Opened 2022-09-15 07:18 UTC by mikrit

2022-09-15 07:19 UTC, jsru commented
Добавляю преподавателя (@dosandk) для код-ревью.

2022-09-15 22:48 UTC, dosandk commented on 02-javascript-data-types/1-sort-strings/index.js
> +  let sortArray = [...arr].sort((a, b) => a.localeCompare(b, ['ru', 'en'], {caseFirst: 'upper'}));
`const`

2022-09-15 22:49 UTC, dosandk commented on 02-javascript-data-types/1-sort-strings/index.js
> +    return sortArray.reverse();
Подумайте как исправить решение таким образом чтобы избавиться от `reverse` и сортировать данные сразу в верном порядке

2022-09-15 22:49 UTC, dosandk commented on 02-javascript-data-types/2-pick/index.js
>  export const pick = (obj, ...fields) => {
good 👍

2022-09-15 22:49 UTC, dosandk commented on 02-javascript-data-types/3-omit/index.js
> +  const omitObj = {};
good 👍

2022-09-15 22:49 UTC, dosandk requested changes
решение `sortStrings` следует поправить!

2022-09-16 07:41 UTC, jsru commented
Добавляю преподавателя (@dosandk) для код-ревью.

2022-09-17 18:17 UTC, dosandk approved these changes
good 👍

2022-09-17 18:18 UTC, merged